--- #YAML:1.0
name:               Net-Discident
version:            v1.0.1
abstract:           query discident.com for DVD details
author:
    - Mark Norman Francis <norm@cackhanded.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Lite:    0
    JSON:          0
    Modern::Perl:  0
    version:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
